#!/usr/bin/env bash
# Attach a true least-privilege inline policy

aws iam put-user-policy \
  --user-name vulnerable-user \
  --policy-name LeastPrivS3ReadOnly \
  --policy-document '{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "s3:ListBucket",
          "s3:GetObject"
        ],
        "Resource": [
          "arn:aws:s3:::example-bucket",
          "arn:aws:s3:::example-bucket/*"
        ]
      }
    ]
  }' \
  --profile admin
