#!/usr/bin/env bash
# Fix with Least Privilege

aws iam detach-user-policy \
  --user-name vulnerable-user \
  --policy-arn arn:aws:iam::aws:policy/AdministratorAccess \
  --profile default

# If custom policy was created:
aws iam detach-user-policy \
  --user-name vulnerable-user \
  --policy-arn arn:aws:iam::AKIA6ISVD3URDYLZ4BN5:policy/EvilAdminPolicy

aws iam delete-policy \
  --policy-arn arn:aws:iam::AKIA6ISVD3URDYLZ4BN5:policy/EvilAdminPolicy
