filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log", "/var/log/auth.log.*"]
      var.convert_timezone: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_locale: ~
  - add_fields:
      when.contains.message: "Failed password"
      target: ''
      fields:
        alert_type: brute_force_attempt
        severity: high
  - add_fields:
      when.contains.message: "Accepted password"
      target: ''
      fields:
        alert_type: successful_login
        severity: info

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
